In [3]:
l = [12312, 123125 , 1235632, -123, 9898]

In [4]:
l

[12312, 123125, 1235632, -123, 9898]

In [6]:
import numpy as np

In [8]:
a = np.array(l)

In [9]:
a

array([  12312,  123125, 1235632,    -123,    9898])

In [11]:
b = np.array([12, 54, 65.3, True, 'a'])

In [12]:
b

array(['12', '54', '65.3', 'True', 'a'], dtype='|S32')

In [13]:
print(b)

['12' '54' '65.3' 'True' 'a']


In [14]:
l.pop()

9898

In [15]:
a.mean()

276168.8

---

In [17]:
l[1:]

[123125, 1235632, -123]

In [18]:
l[0:2]

[12312, 123125]

In [20]:
l[::2]

[12312, 1235632]

In [21]:
#------------------

In [22]:
a[2:]

array([1235632,    -123,    9898])

In [23]:
a[2:4]

array([1235632,    -123])

In [24]:
# when slicing arrays you DO NOT create a copy of an array!

In [25]:
b = a[2:]

In [26]:
b

array([1235632,    -123,    9898])

In [27]:
b[:]

array([1235632,    -123,    9898])

In [28]:
a

array([  12312,  123125, 1235632,    -123,    9898])

In [29]:
c = a.copy() # creates an array copy!

In [30]:
c

array([  12312,  123125, 1235632,    -123,    9898])